# Pf SpotMalaria barcodes configuration

#parameters

regions:
  - Pf3D7_01_v3
  - Pf3D7_02_v3
  - Pf3D7_03_v3
  - Pf3D7_04_v3
  - Pf3D7_05_v3
  - Pf3D7_06_v3
  - Pf3D7_07_v3
  - Pf3D7_08_v3
  - Pf3D7_09_v3
  - Pf3D7_10_v3
  - Pf3D7_11_v3
  - Pf3D7_12_v3
  - Pf3D7_13_v3
  - Pf3D7_14_v3
  - Pf3D7_API_v3
  - Pf3D7_MIT_v3


class: "parasite"
maxEE: "5,5"
trim_right: "10,10"
min_length: 30 
truncQ: "5,5"
max_consist: 10
omegaA: 1e-120
justconcat: 0
platform: "PE"
trimqv: 15


insertseq: configs/refs/pf-spotmal/pfspotmal-mhap-inserts.fasta
primer_fw: configs/refs/pf-spotmal/PfSpotMal_fwd.fasta
primer_rev: configs/refs/pf-spotmal/PfSpotMal_rev.fasta

