#
# pfspotmal-mhap.yaml - configuration file for the MalariaGEN Pf SpotMalaria panel
#

# --- NGS-Pipeline settings ---

optical_dedup: False
instrument: generic
platform: generic
libprep: generic

min_read_qual: 15
read_length: 100

refseq_file: configs/refs/Pf/Pf3D7_v3/Pf3D7_v3.fasta
#knownvariants_dir: configs/refs/Pv/PvP01_v2/known-variants

# perform variant calling on all chromosomes as single workflow
complete_region: Pf3D7_all_v3

# perform targeted variant calling
targetregion_file: configs/refs/pv-vvg/Microhaps_inserts.bed

regions:
  - Pf3D7_01_v3
  - Pf3D7_02_v3
  - Pf3D7_03_v3
  - Pf3D7_04_v3
  - Pf3D7_05_v3
  - Pf3D7_06_v3
  - Pf3D7_07_v3
  - Pf3D7_08_v3
  - Pf3D7_09_v3
  - Pf3D7_10_v3
  - Pf3D7_11_v3
  - Pf3D7_12_v3
  - Pf3D7_13_v3
  - Pf3D7_14_v3
  - Pf3D7_API_v3
  - Pf3D7_MIT_v3

# this is amplicon sequencing, so turn off deduplication
deduplicate: False

# set below to True for new samples (for the purpose of submitting to SRA database)
keep_paired_bam: False

# set below to True for structural variant (SV) analysis such as CNV
keep_final_bam: True

# filter to apply for deduplicated BAM
# read_filters: --remove_FR --remove_RF --remove_FF --remove_RR --remove_trans --remove_unmapped --remove_secondary --remove_supplementary
# for below, we keep FR, RF, FF and RR orientation for future SV analysis
read_filters: --remove_trans --remove_unmapped --remove_secondary --remove_supplementary


reads_trimmer_wf: trimmer_null.smk
reads_mapper_wf: mapper_bwa-mem2.smk

# multistep-variant-caller parameters
prepare_sample_directory_flags: --force
sample_variant_caller_flags: --force --no-config-cascade
joint_variant_caller_flags: --force --no-config-cascade

variant_caller_wf: ssf_varcall_gatk_drag.smk

gatk_calibrate_str: False
haplotypecaller_flags: --max-reads-per-alignment-start 0 --do-not-run-physical-phasing --pileup-detection --dont-use-soft-clipped-bases

# --- end of NGS-Pipeline settings ---

# --- parameters for Microhaplotype settings ---

class: "parasite"
maxEE: "5,5"
trim_right: "10,10"
min_length: 30 
truncQ: "5,5"
max_consist: 10
omegaA: 1e-120
justconcat: 0
platform: "PE"
trimqv: 15

#refs

insertseq: configs/refs/pf-spotmal/pfspotmal-mhap-inserts.fasta
primer_fw: configs/refs/pf-spotmal/PfSpotMal_fwd.fasta
primer_rev: configs/refs/pf-spotmal/PfSpotMal_rev.fasta

# EOF
